In [79]:
# Import
import pandas as pd
from openpyxl import load_workbook
from IPython.display import Image
from sklearn.preprocessing import Imputer
from sklearn import tree
from subprocess import check_call
import re
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score
import graphviz 
from sklearn.model_selection import cross_val_score

In [80]:
data_anarkis_wb = load_workbook(filename = 'data_anarkis.xlsx')
data_anarki_sr = data_anarkis_wb.active
dk = pd.DataFrame(data_anarki_sr.values)
dk = dk[1:]
dk.columns = ['TANGGAL','HARI','UNSUR','TEMPAT']

for index, row in dk.iterrows():
    temp = str(row['TANGGAL'])
    replace=temp.replace('-',' ')
    convert=replace.split()
    year= convert[0:1][0]
    day= convert[2:4][0]
    mont = convert[1:2][0]
    baru = '/'.join([str(day), str(mont), str(year)])
    dk.loc[index, 'TANGGAL'] = baru

In [81]:
tanggal_kriminal = dk['TANGGAL']

    
data_iklim_wb = load_workbook(filename = 'laporan_iklim_harian.xlsx')
data_iklim_sr = data_iklim_wb.active
di = pd.DataFrame(data_iklim_sr.values)
di = di[1:]
di.columns = ['TANGGAL','SUHU','KELEMBABAN','HUJAN']    
di['KRIMINAL'] = 'Tidak Ada'

for index, row in di.iterrows():
    tanggal_sekarang = str(row['TANGGAL'])
    for tanggal in tanggal_kriminal:
        if str(tanggal_sekarang) == str(tanggal):
            di.loc[index, 'KRIMINAL'] = 'Ada'

            
                    
di = di[di.HUJAN != 8888]
di = di[di.HUJAN != 9999]
    
di = di[di.SUHU != 8888]
di = di[di.SUHU != 9999]
    
# di = di[di.HUJAN != 8888]
# di = di[di.HUJAN
di

# tanggal_kriminal

        TANGGAL  SUHU KELEMBABAN HUJAN   KRIMINAL
1    01/01/2016  28.2         83  26.6        Ada
2    02/01/2016  27.1         85     0        Ada
3    03/01/2016  28.4         79  15.6        Ada
4    04/01/2016    29         80     0  Tidak Ada
5    05/01/2016  28.6         83     0  Tidak Ada
6    06/01/2016  28.8         77  11.6  Tidak Ada
7    07/01/2016  29.7         76   0.3  Tidak Ada
8    08/01/2016  29.6         78     0  Tidak Ada
9    09/01/2016    29         81     0  Tidak Ada
10   10/01/2016  29.1         76     0  Tidak Ada
11   11/01/2016  29.8         74     0  Tidak Ada
12   12/01/2016  28.5         82     0  Tidak Ada
13   13/01/2016  28.2         82   5.5  Tidak Ada
14   14/01/2016    29         78   1.2  Tidak Ada
15   15/01/2016  29.4         79     0  Tidak Ada
16   16/01/2016  29.2         77   0.2  Tidak Ada
17   17/01/2016  29.2         76     0  Tidak Ada
18   18/01/2016  29.4         76     0  Tidak Ada
19   19/01/2016  28.7         77     0  Tidak Ada
20   20/01/2016    28         80  30.5  Tidak Ada
21   21/01/2016  28.1         82   0.2  Tidak Ada
22   22/01/2016    29         83   1.8  Tidak Ada
23   23/01/2016  26.7         87  11.4  Tidak Ada
24   24/01/2016  27.7         86  14.7  Tidak Ada
25   25/01/2016  25.9         92  30.8  Tidak Ada
26   26/01/2016  27.8         84   6.7  Tidak Ada
27   27/01/2016    29         81   0.1  Tidak Ada
28   28/01/2016  28.9         81   6.6  Tidak Ada
29   29/01/2016    29         79     0  Tidak Ada
32   01/02/2016  27.7         85     7  Tidak Ada
..          ...   ...        ...   ...        ...
334  29/11/2016  27.1         82   1.6  Tidak Ada
335  30/11/2016  28.5         76     0  Tidak Ada
336  01/12/2016  28.5         73     0  Tidak Ada
338  03/12/2016  28.5         76   6.4  Tidak Ada
339  04/12/2016    25         89   0.4  Tidak Ada
340  05/12/2016  25.8         86  14.8  Tidak Ada
341  06/12/2016  27.7         77   1.7  Tidak Ada
342  07/12/2016  28.8         75     0  Tidak Ada
344  09/12/2016  29.3         71  14.4  Tidak Ada
345  10/12/2016  29.9         71     0  Tidak Ada
346  11/12/2016  27.7         80     0  Tidak Ada
347  12/12/2016  27.2         79   3.1  Tidak Ada
348  13/12/2016  29.4         70     0  Tidak Ada
349  14/12/2016    28         77     0  Tidak Ada
350  15/12/2016  28.6         72   0.8  Tidak Ada
351  16/12/2016  29.2         72     0  Tidak Ada
352  17/12/2016  27.5         84     0  Tidak Ada
353  18/12/2016  28.8         75   7.3  Tidak Ada
354  19/12/2016    28         78     0  Tidak Ada
355  20/12/2016  29.6         71   1.3  Tidak Ada
356  21/12/2016    29         75     0  Tidak Ada
357  22/12/2016  28.4         76   0.4  Tidak Ada
358  23/12/2016  29.2         73   0.5  Tidak Ada
359  24/12/2016  28.8         74     0  Tidak Ada
360  25/12/2016  28.2         75     0  Tidak Ada
362  27/12/2016  28.1         75     7  Tidak Ada
363  28/12/2016  29.8         67     0  Tidak Ada
364  29/12/2016  28.6         75     0  Tidak Ada
365  30/12/2016  28.7         75     0  Tidak Ada
366  31/12/2016  28.6         76     0  Tidak Ada

[339 rows x 5 columns]

In [82]:
j = 0
for index, row in di.iterrows():
    if j <= 270:
        if row['KRIMINAL'] != 'Ada':
            di = di[di.TANGGAL != row['TANGGAL']]
#             print "ads"
    j = j + 1
di

        TANGGAL  SUHU KELEMBABAN HUJAN   KRIMINAL
1    01/01/2016  28.2         83  26.6        Ada
2    02/01/2016  27.1         85     0        Ada
3    03/01/2016  28.4         79  15.6        Ada
52   21/02/2016  28.4         79     0        Ada
54   23/02/2016  28.9         79   0.1        Ada
80   20/03/2016  28.3         89  90.8        Ada
103  12/04/2016  29.1         76     0        Ada
108  17/04/2016  28.9         82     0        Ada
122  01/05/2016  29.1         80   1.4        Ada
128  07/05/2016  29.4         77     0        Ada
131  10/05/2016  29.6         76     1        Ada
137  16/05/2016  29.2         80     0        Ada
139  18/05/2016  29.4         78   0.6        Ada
145  24/05/2016    29         83  19.5        Ada
147  26/05/2016  29.3         77     0        Ada
157  05/06/2016  28.4         81     0        Ada
158  06/06/2016  28.3         79     0        Ada
163  11/06/2016  29.3         76     0        Ada
164  12/06/2016  29.1         74     0        Ada
170  18/06/2016    25         85  57.2        Ada
174  22/06/2016  28.1         80   5.5        Ada
180  28/06/2016  28.7         74     0        Ada
187  05/07/2016  29.2         79     0        Ada
198  16/07/2016  26.3         92     0        Ada
207  25/07/2016  27.7         78     8        Ada
215  02/08/2016  28.2         79  24.5        Ada
220  07/08/2016  28.4         74     0        Ada
230  17/08/2016    29         73     0        Ada
231  18/08/2016  28.8         75     0        Ada
234  21/08/2016  28.5         75     0        Ada
..          ...   ...        ...   ...        ...
334  29/11/2016  27.1         82   1.6  Tidak Ada
335  30/11/2016  28.5         76     0  Tidak Ada
336  01/12/2016  28.5         73     0  Tidak Ada
338  03/12/2016  28.5         76   6.4  Tidak Ada
339  04/12/2016    25         89   0.4  Tidak Ada
340  05/12/2016  25.8         86  14.8  Tidak Ada
341  06/12/2016  27.7         77   1.7  Tidak Ada
342  07/12/2016  28.8         75     0  Tidak Ada
344  09/12/2016  29.3         71  14.4  Tidak Ada
345  10/12/2016  29.9         71     0  Tidak Ada
346  11/12/2016  27.7         80     0  Tidak Ada
347  12/12/2016  27.2         79   3.1  Tidak Ada
348  13/12/2016  29.4         70     0  Tidak Ada
349  14/12/2016    28         77     0  Tidak Ada
350  15/12/2016  28.6         72   0.8  Tidak Ada
351  16/12/2016  29.2         72     0  Tidak Ada
352  17/12/2016  27.5         84     0  Tidak Ada
353  18/12/2016  28.8         75   7.3  Tidak Ada
354  19/12/2016    28         78     0  Tidak Ada
355  20/12/2016  29.6         71   1.3  Tidak Ada
356  21/12/2016    29         75     0  Tidak Ada
357  22/12/2016  28.4         76   0.4  Tidak Ada
358  23/12/2016  29.2         73   0.5  Tidak Ada
359  24/12/2016  28.8         74     0  Tidak Ada
360  25/12/2016  28.2         75     0  Tidak Ada
362  27/12/2016  28.1         75     7  Tidak Ada
363  28/12/2016  29.8         67     0  Tidak Ada
364  29/12/2016  28.6         75     0  Tidak Ada
365  30/12/2016  28.7         75     0  Tidak Ada
366  31/12/2016  28.6         76     0  Tidak Ada

[101 rows x 5 columns]

In [83]:
rata2hujan = list()
i = 0
n = 0
for index, row in di.iterrows():
    n = n + 1
    rata2hujan.append(row['HUJAN'])
    if row['KRIMINAL'] == 'Ada':
        i = i + 1;
    
rata2h = sum(rata2hujan)/n
minhujan = rata2h * 85/100
maxhujan = rata2h * 115/100

for index, row in di.iterrows():
    if row['HUJAN'] >= minhujan:
        di.loc[index, 'HUJAN'] = 1
    else:
        di.loc[index, 'HUJAN'] = 0

di = di.drop('TANGGAL', 1)
# print di
        
    
dtrain = di[1:80]
# dtrain

In [84]:
di

     SUHU KELEMBABAN HUJAN   KRIMINAL
1    28.2         83     1        Ada
2    27.1         85     0        Ada
3    28.4         79     1        Ada
52   28.4         79     0        Ada
54   28.9         79     0        Ada
80   28.3         89     1        Ada
103  29.1         76     0        Ada
108  28.9         82     0        Ada
122  29.1         80     0        Ada
128  29.4         77     0        Ada
131  29.6         76     0        Ada
137  29.2         80     0        Ada
139  29.4         78     0        Ada
145    29         83     1        Ada
147  29.3         77     0        Ada
157  28.4         81     0        Ada
158  28.3         79     0        Ada
163  29.3         76     0        Ada
164  29.1         74     0        Ada
170    25         85     1        Ada
174  28.1         80     1        Ada
180  28.7         74     0        Ada
187  29.2         79     0        Ada
198  26.3         92     0        Ada
207  27.7         78     1        Ada
215  28.2         79     1        Ada
220  28.4         74     0        Ada
230    29         73     0        Ada
231  28.8         75     0        Ada
234  28.5         75     0        Ada
..    ...        ...   ...        ...
334  27.1         82     0  Tidak Ada
335  28.5         76     0  Tidak Ada
336  28.5         73     0  Tidak Ada
338  28.5         76     1  Tidak Ada
339    25         89     0  Tidak Ada
340  25.8         86     1  Tidak Ada
341  27.7         77     0  Tidak Ada
342  28.8         75     0  Tidak Ada
344  29.3         71     1  Tidak Ada
345  29.9         71     0  Tidak Ada
346  27.7         80     0  Tidak Ada
347  27.2         79     0  Tidak Ada
348  29.4         70     0  Tidak Ada
349    28         77     0  Tidak Ada
350  28.6         72     0  Tidak Ada
351  29.2         72     0  Tidak Ada
352  27.5         84     0  Tidak Ada
353  28.8         75     1  Tidak Ada
354    28         78     0  Tidak Ada
355  29.6         71     0  Tidak Ada
356    29         75     0  Tidak Ada
357  28.4         76     0  Tidak Ada
358  29.2         73     0  Tidak Ada
359  28.8         74     0  Tidak Ada
360  28.2         75     0  Tidak Ada
362  28.1         75     1  Tidak Ada
363  29.8         67     0  Tidak Ada
364  28.6         75     0  Tidak Ada
365  28.7         75     0  Tidak Ada
366  28.6         76     0  Tidak Ada

[101 rows x 4 columns]

In [85]:
y = dtrain['KRIMINAL'].values
# features = di['SUHU','KELEMBABAN','HUJAN']
features_columns = ['SUHU','HUJAN']
features = dtrain[list(features_columns)].values
imp = Imputer(axis=0)
x = imp.fit_transform(features)
clf = tree.DecisionTreeClassifier(criterion="entropy")
clf = clf.fit(x,y)

import cPickle as pkl
pkl.dump(clf, open('tree.pkl', 'wb'))

# from sklearn.naive_bayes import GaussianNB
# gnb = GaussianNB()
# gnb_fit = gnb.fit(x, y)

In [86]:
di
d_test = di[80:]
# d_test = d_test.sample(n=30)

y_true = d_test['KRIMINAL'].values
y_true

features_columns = ['SUHU','HUJAN']
features = d_test[list(features_columns)].values

features
y_predict = clf.predict(features)
# y_predict

clf.predict([[27.9, 1]])

array(['Tidak Ada'], dtype=object)

In [87]:
result = confusion_matrix(y_true, y_predict, labels=["Tidak Ada","Ada"])
result

array([[ 9, 12],
       [ 0,  0]])

In [88]:
akurasi = accuracy_score(y_true, y_predict)
akurasi

0.42857142857142855

In [89]:
presisi = precision_score(y_true, y_predict, average='macro')
presisi

0.5

In [90]:
recall = recall_score(y_true, y_predict, average='macro')
recall

0.21428571428571427

In [91]:
with open("tree.dot", "w") as f:
    f = tree.export_graphviz(clf, out_file=f, feature_names=features_columns,
                            filled=True, rounded=True,
                            special_characters=True)

from subprocess import check_call
check_call(['dot','-Tpng','tree.dot','-o','OutputFile.png'])





# dot_data = tree.export_graphviz(clf, out_file=None, feature_names=features_columns,
#                             filled=True, rounded=True,
        
#                                 special_characters=True)
# graph = graphviz.Source(dot_data)
# graph
# graph.draw('file.png')

0